# IMDB Movie Rating  SENTIMENT ANALYSIS
- DATA SET - IMDBI DATA SET

In [4]:
# importing  necessary modules

import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')

In [5]:
data = pd.read_csv(r"C:\Users\Tuhin\OneDrive\Desktop\IMDB_dataset.csv");
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
df = data.copy()
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [8]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [9]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [11]:
df.shape

(50000, 2)

# Text Processing

In [12]:
# Tokeniztion
#Normalization
#join

df['review']=df['review'].apply(lambda x : ' '.join(word .lower() for word in word_tokenize(x) if word.isalpha()))
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there a family where a little boy ja...  negative
4  petter mattei love in the time of money is a v...  positive

In [13]:
#Remove stopwords

# Remove stopwords
stop = stopwords.words('english')
df['review'] = df['review'].apply(lambda x: ' '.join(word for word in x.split() if word not in stop))
df.head()

                                              review sentiment
0  one reviewers mentioned watching oz episode ho...  positive
1  wonderful little production br br filming tech...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically family little boy jake thinks zombie...  negative
4  petter mattei love time money visually stunnin...  positive

In [14]:

# Word Vectorization
vectorizer = TfidfVectorizer()

In [16]:
# split dataset
#Setting target and feature

#Vactorization
X = vectorizer.fit_transform(df['review'])
y = df['sentiment']

#Train test split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)

In [17]:
# Build and Train Model

model = MultinomialNB()
model.fit(X_train , y_train)

MultinomialNB()

In [18]:
# prediction
y_predict = model.predict(X_test)
accuracy = metrics.accuracy_score(y_test , y_predict)
print(f'Model accuracy: {accuracy*100:.2f}%')

Model accuracy: 86.72%