# Email Spam or Ham

In [2]:
# importing  necessary modules

import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')

In [4]:
# load Data Set

data = pd.read_csv(r"C:\Users\Tuhin\OneDrive\Desktop\spam.csv")
data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
# Back up data
df = data.copy()
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
# For information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [7]:
# For Describing
df.describe()

       Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

# Text processing

In [8]:
# Tokeniztion
#Normalization
#join

df['Message']=df['Message'].apply(lambda x : ' '.join(word .lower() for word in word_tokenize(x) if word.isalpha()))
df.head()

  Category                                            Message
0      ham  go until jurong point crazy available only in ...
1      ham                            ok lar joking wif u oni
2     spam  free entry in a wkly comp to win fa cup final ...
3      ham        u dun say so early hor u c already then say
4      ham  nah i do think he goes to usf he lives around ...

In [9]:
#Remove stopwords

# Remove stopwords
stop = stopwords.words('english')
df['Message'] = df['Message'].apply(lambda x: ' '.join(word for word in x.split() if word not in stop))
df.head()

  Category                                            Message
0      ham  go jurong point crazy available bugis n great ...
1      ham                            ok lar joking wif u oni
2     spam  free entry wkly comp win fa cup final tkts may...
3      ham                u dun say early hor u c already say
4      ham             nah think goes usf lives around though

In [11]:
# Word Vectorization
vectorizer = TfidfVectorizer()

In [12]:
# split dataset
#Setting target and feature

#Vactorization
X = vectorizer.fit_transform(df['Message'])
y = df['Category']

#Train test split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)

In [14]:
# Build and Train Model

model = MultinomialNB()
model.fit(X_train , y_train)

MultinomialNB()

In [15]:
# prediction
y_predict = model.predict(X_test)
accuracy = metrics.accuracy_score(y_test , y_predict)
print(f'Model accuracy: {accuracy*100:.2f}%')

Model accuracy: 97.13%